version: "3.8"
services:
  frontend:
    build: ./Front End
    ports:
      - 5173:5173
    depends_on:
      - api

  api:
    build: ./API
    ports:  
      - 8080:8080
    depends_on:
      - database 

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: gosaas_reporting_service
    ports:
      - 5433:5432 
    volumes:
      - gosaas_reporting_service:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672    # Port for RabbitMQ communication
      - 15672:15672  # Port for RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  gosaas_reporting_service:



