export enum SourceConnectionType {
  SQL = "sql",
  POSTGRES = "postgresql",
  MYSQL = "mysql",
  MARIADB = "mariadb",
  ORACLE = "oracle",
  SQLSERVER = "sqlserver",
  SQLITE = "sqlite",
  H2 = "h2",
  DB2 = "db2",
  DERBY = "derby",
  HSQLDB = "hsqldb",
  FIREBIRD = "firebirdsql",
  CASSANDRA = "cassandra",
  MONGO = "mongo",
  INFORMIX = "informix",
  SYBASE = "sybase",
  AWSATHENA = "awsathena",
  NEO4J = "neo4j",
  SNOWFLAKE = "snowflake",
  REDSHIFT = "redshift",
  PRESTO = "presto"
}