## Google OAuth2
spring:
  #  security:
  #    oauth2:
  #      client:
  #        registration:
  #          google:
  #            client-id: ${CLIENT_ID}
  #            client-secret: ${CLIENT_SECRET}

  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/gosaas_reporting_service
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Server
frontend:
  url: ${HOST_FRONTEND_URL}


# Logging
logging:
  file:
    name: ./app.log
    max-size: 10MB
  pattern:
    console: "[%d{ISO8601}] [%p] [%X{traceid}] %m%n"

  # testing logging and deleting
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 0
