# Google OAuth2
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your-google-client-id
            client-secret: your-google-client-secret

# profiles
  profiles:
    active: your-yml-file-tag

  # Database
  datasource:
    url: jdbc:your-database-url
    username: your-database-username
    password: your-database-password
    driver-class-name: your-database-driver-class-name
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: your-hibernate-dialect
        format_sql: true

# Server
frontend:
  url: your-frontend-url

# Logging
logging:
  file:
    name: your-log-file-name
    max-size: your-log-file-max-size
  pattern:
    console: your-log-pattern

  # testing logging and deleting
  logback:
    rollingpolicy:
      max-file-size: file-max-size
      max-history: file-max-history

  # AWS Config
  aws:
    access:
      key: your-aws-access-key
    secret:
      key: your-aws-secret-key
    region: your-aws-region
    bucket:
      name: your-aws-bucket-name
